import { test, expect } from "@playwright/test";
import { createCamp } from "../../packages/core/src";
test("campsite shows current work, retains collapsed decisions and handles lost connectivity", async ({ page }) => {
  const now = new Date().toISOString();
  const c = createCamp("camp-display", { name: "Activity fixture", focus: "america" }, "operator", now);
  c.status = "running";
  c.revision = 1;
  c.cultural!.tasks.push({ id: "task", publicationId: "p", role: "referencer", dependsOn: [], status: "waiting_input", waitKind: "handoff", output: "Please check the handoff", recoveryAttempts: 2, createdAt: now });
  c.messages.push({ id: "recent", at: now, senderId: "finder", recipientId: "camp", text: "I found a passage in the original edition." });
  let offline = false;
  await page.route(/\/api\/camps(?:\/|$)/, async route => {
    if (offline) return route.fulfill({ status: 503, json: { error: "Local camp executor is offline" } });
    const path = new URL(route.request().url()).pathname;
    const data = path.endsWith("/session") ? { actor: { id: "operator" } } : path.endsWith("/revision") ? { revision: c.revision } : path.endsWith(c.id) ? c : { camps: [c] };
    await route.fulfill({ json: data });
  });
  await page.goto("/");
  await expect(page.getByRole("status")).toContainText("Needs you");
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await expect(page.locator(".camp-actions")).toContainText("Noor needs help");
  await expect(page.locator(".camp-bubble.dialogue")).toContainText("original edition");
  await page.getByRole("button", { name: "Collapse action", exact: true }).click();
  c.revision++;
  await page.waitForTimeout(3500);
  await expect(page.getByRole("button", { name: "Expand action", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Expand action", exact: true }).click();
  await page.getByRole("button", { name: "Help agent", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).not.toBeVisible();
  c.cultural!.tasks[0].status = "done";
  c.messages[0].at = "2020-01-01T00:00:00Z";
  c.revision++;
  await expect(page.locator(".camp-actions")).toHaveCount(0);
  await expect(page.locator(".camp-bubble.dialogue")).toHaveCount(0);
  offline = true;
  await expect(page.getByRole("status")).toContainText("Connection lost", { timeout: 26000 });
  await expect(page.getByRole("button", { name: "Pause camp", exact: true })).toBeDisabled();
});
