[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 %(ENV_RESOLUTION)s -ac +extension GLX +render -noreset
priority=10
autorestart=true

[program:xfce]
command=/usr/bin/startxfce4
environment=DISPLAY=":99"
priority=20
autorestart=true
user=openclaw

[program:x11vnc]
command=/usr/bin/x11vnc -display :99 -nopw -forever -shared
priority=30
autorestart=true
user=openclaw
